/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './index';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/forms/src/directives';
import * as import4 from '@angular/forms/src/form_providers';
import * as import5 from '@angular/http/src/http_module';
import * as import6 from '@angular/common/src/localization';
import * as import7 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import8 from '@angular/http/src/backends/browser_xhr';
import * as import9 from '@angular/http/src/base_response_options';
import * as import10 from '@angular/http/src/backends/xhr_backend';
import * as import11 from '@angular/http/src/base_request_options';
import * as import12 from '@angular/core/src/di/injector';
import * as import13 from '@angular/core/src/i18n/tokens';
import * as import14 from '@angular/http/src/interfaces';
import * as import15 from '@angular/http/src/http';
class LibStarterModuleInjector extends import0.NgModuleInjector<import1.LibStarterModule> {
  _CommonModule_0:import2.CommonModule;
  _InternalFormsSharedModule_1:import3.InternalFormsSharedModule;
  _FormsModule_2:import4.FormsModule;
  _HttpModule_3:import5.HttpModule;
  _LibStarterModule_4:import1.LibStarterModule;
  __NgLocalization_5:import6.NgLocaleLocalization;
  __RadioControlRegistry_6:import7.RadioControlRegistry;
  __BrowserXhr_7:import8.BrowserXhr;
  __ResponseOptions_8:import9.BaseResponseOptions;
  __XSRFStrategy_9:any;
  __XHRBackend_10:import10.XHRBackend;
  __RequestOptions_11:import11.BaseRequestOptions;
  __Http_12:any;
  constructor(parent:import12.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_5():import6.NgLocaleLocalization {
    if ((this.__NgLocalization_5 == null)) { (this.__NgLocalization_5 = new import6.NgLocaleLocalization(this.parent.get(import13.LOCALE_ID))); }
    return this.__NgLocalization_5;
  }
  get _RadioControlRegistry_6():import7.RadioControlRegistry {
    if ((this.__RadioControlRegistry_6 == null)) { (this.__RadioControlRegistry_6 = new import7.RadioControlRegistry()); }
    return this.__RadioControlRegistry_6;
  }
  get _BrowserXhr_7():import8.BrowserXhr {
    if ((this.__BrowserXhr_7 == null)) { (this.__BrowserXhr_7 = new import8.BrowserXhr()); }
    return this.__BrowserXhr_7;
  }
  get _ResponseOptions_8():import9.BaseResponseOptions {
    if ((this.__ResponseOptions_8 == null)) { (this.__ResponseOptions_8 = new import9.BaseResponseOptions()); }
    return this.__ResponseOptions_8;
  }
  get _XSRFStrategy_9():any {
    if ((this.__XSRFStrategy_9 == null)) { (this.__XSRFStrategy_9 = import5._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_9;
  }
  get _XHRBackend_10():import10.XHRBackend {
    if ((this.__XHRBackend_10 == null)) { (this.__XHRBackend_10 = new import10.XHRBackend(this._BrowserXhr_7,this._ResponseOptions_8,this._XSRFStrategy_9)); }
    return this.__XHRBackend_10;
  }
  get _RequestOptions_11():import11.BaseRequestOptions {
    if ((this.__RequestOptions_11 == null)) { (this.__RequestOptions_11 = new import11.BaseRequestOptions()); }
    return this.__RequestOptions_11;
  }
  get _Http_12():any {
    if ((this.__Http_12 == null)) { (this.__Http_12 = import5.httpFactory(this._XHRBackend_10,this._RequestOptions_11)); }
    return this.__Http_12;
  }
  createInternal():import1.LibStarterModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._InternalFormsSharedModule_1 = new import3.InternalFormsSharedModule();
    this._FormsModule_2 = new import4.FormsModule();
    this._HttpModule_3 = new import5.HttpModule();
    this._LibStarterModule_4 = new import1.LibStarterModule();
    return this._LibStarterModule_4;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_1; }
    if ((token === import4.FormsModule)) { return this._FormsModule_2; }
    if ((token === import5.HttpModule)) { return this._HttpModule_3; }
    if ((token === import1.LibStarterModule)) { return this._LibStarterModule_4; }
    if ((token === import6.NgLocalization)) { return this._NgLocalization_5; }
    if ((token === import7.RadioControlRegistry)) { return this._RadioControlRegistry_6; }
    if ((token === import8.BrowserXhr)) { return this._BrowserXhr_7; }
    if ((token === import9.ResponseOptions)) { return this._ResponseOptions_8; }
    if ((token === import14.XSRFStrategy)) { return this._XSRFStrategy_9; }
    if ((token === import10.XHRBackend)) { return this._XHRBackend_10; }
    if ((token === import11.RequestOptions)) { return this._RequestOptions_11; }
    if ((token === import15.Http)) { return this._Http_12; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const LibStarterModuleNgFactory:import0.NgModuleFactory<import1.LibStarterModule> = new import0.NgModuleFactory(LibStarterModuleInjector,import1.LibStarterModule);